### ISSUE TITLE
Make the submission form scrollable

### ISSUE THREAD

**Issue by elviscat** [biosemantics/MicroPIEWeb#1]
Currently, due to the monitor resolution the submit button of submission form cannot be seen when first loaded. I use FramePanel (GWT) to build the interface form and it is not scrollable. What I want to implement is similar with this example: http://www.sencha.com/examples/#ExamplePlace:formsexample. The source code of the submission form is here: 
https://github.com/biosemantics/MicroPIEWeb/blob/master/src/main/java/edu/arizona/biosemantics/micropie/web/client/MyView.java
Do you have any idea to improve that?

**Comment by rodenhausen** [comment]
Use VerticalLayoutContainer instead of VerticalPanel. The example that you
referred to uses exactly that, but your code doesn't.
To allow scrolling you can configure the VerticalLayoutContainer with
.setScrollMode(ScrollMode.AUTO), see
http://dev.sencha.com/deploy/gxt-3.0.0/javadoc/gxt/com/sencha/gxt/widget/core/client/container/VerticalLayoutContainer.html

**Comment by elviscat** [comment]
Used your suggested way but it still doesn't work. Also I check the example again. Is it possible to make rootPanel scrollable?

**Comment by rodenhausen** [comment]
Tried code on my end. Couldn't reproduce the problem in Chrome or FF.

**Comment by elviscat** [comment]
I grabbed two snapshots from ETC and MicroPIEWeb.

When the browser window is very small (simulate low monitor resolution, ex:800*600), MicroPIEWeb didn't show scroll bar when first loading but ETC did. Could you send me the source code link of ETC home page so that I can learn how do you wrap it?

![2015-01-21_0912](https://cloud.githubusercontent.com/assets/1954101/5839791/e0403f66-a14d-11e4-964b-dc3350c33ad9.png)

![2015-01-21_0913](https://cloud.githubusercontent.com/assets/1954101/5839792/e20afdd6-a14d-11e4-9d39-47b61870c80b.png)

**Comment by hongcui** [comment]
look into
https://github.com/biosemantics/etc-site/tree/master/src/main/java/edu/arizona/biosemantics/etcsite/client/content/home

On Wed, Jan 21, 2015 at 9:17 AM, elviscat notifications@github.com wrote:

> I grabbed two snapshots from ETC and MicroPIEWeb.
> 
> When the browser window is very small (simulate low monitor resolution,
> ex:800*600), MicroPIEWeb didn't show scroll bar when first loading but ETC
> did. Could you send me the source code link of ETC home page so that I can
> learn how do you wrap it?
> 
> [image: 2015-01-21_0912]
> https://cloud.githubusercontent.com/assets/1954101/5839791/e0403f66-a14d-11e4-964b-dc3350c33ad9.png
> 
> [image: 2015-01-21_0913]
> https://cloud.githubusercontent.com/assets/1954101/5839792/e20afdd6-a14d-11e4-9d39-47b61870c80b.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biosemantics/MicroPIEWeb/issues/1#issuecomment-70866861
> .

## 

Hong Cui, Ph.D http://sirls.arizona.edu/hongcui
Associate Professor, Information Technology
School of Information Resource and Library Science
http://sirls.arizona.edu
University of Arizona

Member of Plazi.org

**Comment by rodenhausen** [comment]
Here's the relevant etc source
https://github.com/biosemantics/etc-site/blob/master/src/main/java/edu/arizona/biosemantics/etcsite/client/layout/EtcSiteView.ui.xml

**Comment by rodenhausen** [comment]
Also, if you can you should stick to only GWT or only GXT containers /
panels as they are not 100% compatible with regard to layouting, resizing,
.. hence scrolling.
